config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :events
      resources :groups
      resources :readings
      resources :sessions

      root to: "users#index"
    end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'events#index'
  resources :readings
  resources :sessions
  resources :groups
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reading.rb
# frozen_string_literal: true

class Reading < ApplicationRecord
  belongs_to :session
  validates :number, presence: true
end

app/controllers/admin/readings_controller.rb
module Admin
  class ReadingsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Reading.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Reading.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/readings_controller.rb
# frozen_string_literal: true

class ReadingsController < ApplicationController
  before_action :set_reading, only: %i[show edit update destroy]

  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.where(session_id: params[:session])
    authorize @readings
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
    authorize Reading
  end

  # GET /readings/new
  def new
    @reading = Reading.new(session_id: params['session'])
    authorize @reading
  end

  # GET /readings/1/edit
  def edit
    authorize Reading
  end

  # POST /readings
  # POST /readings.json
  def create
    authorize Reading
    # TODO: REFACTOR: I think some of this can be moved to the model
    # Find all readings based on given params
    # Update all found readings in a transaction
    # Create new readings for all remaining params
    set_readings
    assing_reading_params
    create_objects_for_new_records
    reject_invalid
    select_valid
    @readings.map(&:save)

    respons(@rejected.empty?)
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    authorize @reading
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    authorize @reading
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_session
    @session = Session.find(session_params[:id])
  end

  def session_params
    params.require(:session).permit(:id)
  end

  def set_readings
    reading_numbers = readings_params[:readings].map { |p| p [:number] }
    @readings = Reading.where(session: session_params[:id],
                              number: reading_numbers)
  end

  def assing_reading_params
    @readings = @readings.map do |reading|
      reading.assign_attributes(find_param_by_number(reading))
      reading
    end
  end

  def find_param_by_number(reading)
    readings_params[:readings].find do |p|
      p[:number].to_i == reading.number
    end
  end

  def set_reading
    @reading = Reading.find(params[:id])
  end

  def create_objects_for_new_records
    # Reject parameters which have a matching db record
    remaining = readings_params[:readings].reject do |p|
      @readings.map(&:number).include?(p[:number].to_i)
    end
    remaining.each do |param|
      @readings << Reading.new(param)
    end
  end

  def reject_invalid
    @rejected = @readings.reject(&:valid?)
  end

  def respons(success)
    respond_to do |format|
      if success
        format.json { render json: @readings, status: :created }
      else
        format.json do
          render json: @rejected.map(&:errors),
                 status: :unprocessable_entity
        end
      end
    end
  end

  def save_readings
    Reading.transaction do
      @valid_readings.map(&:save)
    end
  end

  def select_valid
    @valid_readings = @readings.select(&:changed?).select(&:valid?)
  end

  def readings_params
    params.require(:reading).permit(readings: %i[number
                                                 readings
                                                 car_class
                                                 session_id])
  end

  def reading_params
    params.require(:reading).permit(:number, :car_class, :readings)
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
<%= form_with(model: reading, local: true) do |form| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if reading.session_id.nil? %>
    <div class="field">
      <%= form.label :session_id %>
      <%= form.text_field :session_id %>
    </div>
  <% else %>
    <%= form.hidden_field :session_id %>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :readings %>
    <%= form.text_field :readings %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Readings</h1>

<table>
  <thead>
    <tr>
      <th>Report</th>
      <th>Number</th>
      <th>Class</th>
      <th>Readings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readings.each do |reading| %>
      <tr>
        <td><%= reading.session.id %></td>
        <td><%= reading.number %></td>
        <td><%= reading.class %></td>
        <td><%= reading.readings %></td>
        <td><%= link_to 'Show', reading %></td>
        <td><%= link_to 'Edit', edit_reading_path(reading) %></td>
        <td><%= link_to 'Destroy', reading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reading', new_reading_path %>

app/views/readings/new.html.erb
<h1>New Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Report:</strong>
  <%= @reading.session.id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @reading.number %>
</p>

<p>
  <strong>Class:</strong>
  <%= @reading.class %>
</p>

<p>
  <strong>Readings:</strong>
  <%= @reading.readings %>
</p>

<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>